import networkx as nx
import random as random
import matplotlib.pyplot as plt
from itertools import combinations
from grafo_complemento import *
from convexity_geodetic import *
from grafo_complemento import *
from plotando_grafos import *
from prisms import *
from split import *